import "./globals.css";

import { GeistSans } from "geist/font/sans";
import { ReactNode } from "react";

import Providers from "@/app/providers";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased", GeistSans.className)}>
        <Providers>
          <main className="flex min-h-screen flex-1 flex-col">{children} </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
